### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by kneasle** [kneasle/jigsaw#1]
## Needed for first demo
- [x] Allow frags to be:
  - [x] moved
  - [x] deleted
  - [x] joined
- [x] Allow user to set part heads
- [x] Allow user to choose what frag gets added
## Essential
- [x] Have some kind of understanding of what methods are
- [x] Make music highlighting depend on what proportion of parts are musical, rather than how many parts
- [x] Adding whilst hovering a leftover row should append to the fragment
- [x] Allow user to specify which method to add (tho not using a pie menu)
- [x] Allow the following to be defined:
  - [x] Methods
  - [x] Method ruleoffs/labelled locations
  - [x] Calls
- [x] Allow calls to be labelled
- [x] Allow frags to be... :
  - [x] transposed
  - [x] muted/soloed
  - [x] extended
- [x] Allow calls to be changed
- [x] Implement group expansion for the part heads
- [ ] Add nice UI for the following:
  - [x] Methods
  - [ ] Method ruleoffs/labelled locations
  - [ ] Calls
- [x] Allow collapsing of leads/courses/blocks
- [ ] Allow entire state to be saved to cookie(s)

## Good to have
- [x] Have view update when transposing (but not update the undo history until the user is finished)
- [x] Convert build script to Python
- [ ] Highlight false rows red
- [ ] Add minimap
- [ ] Display greyed-out calling positions for every call location (on both sides, and handling different calls)
- [ ] Allow `Frag`s to be extended upwards
- [ ] Have some form of grid snapping when the user is moving fragments
- [ ] Make `s` snap to lead ends, and `shift-S` force a split wherever
- [ ] Make falseness colours stay consistent when groups are changed
- [ ] Atw indicator
- [ ] Allow user to 'tag' comp states so that they can be loaded later
- [ ] Implement pie menus
- [ ] Copy rows
- [ ] Shift-drag fragments to join them even if they don't connect (i.e. drag top row onto bottom row to update upwards, and drag bottom row to top row to update downwards)
- [ ] Switch `(JS, CSS)` to `(TypeScript, SASS)` and add the compilation to `build.py`
- [ ] Use a templating engine (probably [Tera](https://tera.netlify.app/)) to generate the HTML
- [ ] Make a proc macro to export TypeScript versions of the `Derived*` structs so that we get automatic type checking without having to maintain two independent copies of the same types.
